"""crear_tablas_mediciones

Revision ID: e405d1e4c9ad
Revises: 48d728f750a5
Create Date: 2026-05-04 23:37:35.801072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e405d1e4c9ad'
down_revision: Union[str, None] = '48d728f750a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('total_registros', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_csv_id'), 'archivos_csv', ['id'], unique=False)
    op.create_table('mediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contenido_agua', sa.Float(), nullable=True),
    sa.Column('rad_solar', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humedad_pct', sa.Float(), nullable=True),
    sa.Column('vel_viento', sa.Float(), nullable=True),
    sa.Column('vel_rafagas', sa.Float(), nullable=True),
    sa.Column('dir_viento', sa.Float(), nullable=True),
    sa.Column('lluvia_mm', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos_csv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediciones_archivo_id'), 'mediciones', ['archivo_id'], unique=False)
    op.create_index(op.f('ix_mediciones_id'), 'mediciones', ['id'], unique=False)
    op.create_index(op.f('ix_mediciones_timestamp'), 'mediciones', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediciones_timestamp'), table_name='mediciones')
    op.drop_index(op.f('ix_mediciones_id'), table_name='mediciones')
    op.drop_index(op.f('ix_mediciones_archivo_id'), table_name='mediciones')
    op.drop_table('mediciones')
    op.drop_index(op.f('ix_archivos_csv_id'), table_name='archivos_csv')
    op.drop_table('archivos_csv')
    # ### end Alembic commands ###
